# Generated by Django 4.2.7 on 2023-12-27 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_passengers', models.PositiveIntegerField()),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passengers.passengerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=100)),
                ('days_available', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=100)),
                ('departure_station', models.CharField(max_length=100)),
                ('destination_station', models.CharField(max_length=100)),
                ('departure_time', models.TimeField(auto_now=True)),
                ('fare', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('available_seats', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway_staff.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway_staff.trains'),
        ),
    ]
