# Generated by Django 4.2.7 on 2023-12-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_staff', '0003_rename_trains_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='days_available',
        ),
        migrations.DeleteModel(
            name='DayOfWeek',
        ),
        migrations.AddField(
            model_name='train',
            name='days_available',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='Monday', max_length=100),
        ),
    ]
