# Generated by Django 4.2.7 on 2023-12-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_staff', '0004_remove_train_days_available_delete_dayofweek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='days_available',
            field=models.CharField(max_length=100),
        ),
    ]
