# Generated by Django 4.2.7 on 2023-12-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railway_staff', '0005_alter_train_days_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='train',
            name='train_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway_staff.trainnames'),
        ),
    ]
