# Generated by Django 4.2.7 on 2024-01-03 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('railway_staff', '0013_remove_train_day_of_week_train_friday_train_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='reaching_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
