# Generated by Django 4.2.7 on 2024-01-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_staff', '0017_booking_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='first_ac_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='train',
            name='general_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='train',
            name='second_ac_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='train',
            name='sleeper_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='train',
            name='third_ac_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
