# Generated by Django 4.2.7 on 2024-01-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway_staff', '0019_alter_train_first_ac_fare_alter_train_general_fare_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='first_ac_fare',
        ),
        migrations.RemoveField(
            model_name='train',
            name='general_fare',
        ),
        migrations.RemoveField(
            model_name='train',
            name='second_ac_fare',
        ),
        migrations.RemoveField(
            model_name='train',
            name='sleeper_fare',
        ),
        migrations.RemoveField(
            model_name='train',
            name='third_ac_fare',
        ),
    ]
