# Generated by Django 4.2.7 on 2024-01-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway_staff', '0022_remove_passengerinformation_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengerinformation',
            old_name='email',
            new_name='passenger_email',
        ),
    ]
