# Generated by Django 4.2.7 on 2024-01-22 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railway_staff', '0039_alter_train_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='train_sch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='railway_staff.trainschedule'),
        ),
    ]
