# Generated by Django 4.2.7 on 2024-01-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_staff', '0040_booking_train_sch'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerinformation',
            name='seat_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
