# Generated by Django 4.2.7 on 2024-01-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_staff', '0041_passengerinformation_seat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerinformation',
            name='seat_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
